//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubApiDemo.Descriptions.GitHubApiDemo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SearchIssuesBroker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchIssuesBroker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHubApiDemo.Descriptions.GitHubApiDemo.SearchIssuesBroker", typeof(SearchIssuesBroker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value that determines if the search results are limited to issues in only archived or only non-archived repositories.  The default is to include both archived and non-archived repositories..
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues assigned to the specified user..
        /// </summary>
        internal static string Assignee {
            get {
                return ResourceManager.GetString("Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues created by the specified user..
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues based on the branch they are merging into..
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues closed during the specified range of dates..
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues commented on by the specified user..
        /// </summary>
        internal static string Commenter {
            get {
                return ResourceManager.GetString("Commenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues that have a number of comments within the specified range..
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues created during the specified range of dates..
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to exclude the specified criteria..
        /// </summary>
        internal static string Exclusions {
            get {
                return ResourceManager.GetString("Exclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues descended from the specified branch..
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues where the specified field(s) contain the search term (Term)..
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues assigned to, created by, commented on, or mentioning the specified user..
        /// </summary>
        internal static string Involves {
            get {
                return ResourceManager.GetString("Involves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues that match one or more of the specified states.  For example, issues that are open, closed, merged, unmerged, etc..
        /// </summary>
        internal static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues with the specified labels.  The labels are specified as a comma-separated list..
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues that are in repositories that match the specified programming language..
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues mentioning the specified user..
        /// </summary>
        internal static string Mentions {
            get {
                return ResourceManager.GetString("Mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues that were merged within the specified date range..
        /// </summary>
        internal static string Merged {
            get {
                return ResourceManager.GetString("Merged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues with the specified milestone..
        /// </summary>
        internal static string Milestone {
            get {
                return ResourceManager.GetString("Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues missing the specified metadata.  For example, issues that lack a label, milestone, or assigned user..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues in the specified set of repositories.  The repositories are specified as a comma-separated list, using an &quot;owner/name&quot; format for each individual repository..
        /// </summary>
        internal static string Repos {
            get {
                return ResourceManager.GetString("Repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort the search results by the specified field..
        /// </summary>
        internal static string SortField {
            get {
                return ResourceManager.GetString("SortField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues in the specified state (e.g. open or closed)..
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues with the specified commitment status (e.g. pending, success, error, failure, etc.)..
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues mentioning the specified team (within an organization)..
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues of the specified type (e.g. issues or pull requests)..
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues updated with the specified range of dates..
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the search results to issues in repositories owned by the specified user..
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
