//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardcodet.Wpf.Samples
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Script
    {
        public int ScriptID { get; set; }
        public string ScriptName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public int NumberTimesExecuted { get; set; }
        public int NumberTimesDownloaded { get; set; }
        public Nullable<System.DateTime> LastExecutedDate { get; set; }
        public int NumberActionsSaved { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string SetupInstructions { get; set; }
        public int NumberTimesExecutedCorrectly { get; set; }
        public int NumberTimesExecutedIncorrectly { get; set; }
        public int PercentCorrect { get; set; }
        public int NumberTimesCancelled { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Category4 { get; set; }
        public string Category5 { get; set; }
        public string Executable { get; set; }
        public string ExecuteContent { get; set; }
    }
}
